### ISSUE TITLE
Remove ThirdParty/ITK folder

### ISSUE THREAD

**Issue by schuhschuh** [MIRTK/DrawEM#1]
@amakropoulos Binary files shouldn't be in any source repository. It's also not so good to suggest that ITK would be included. I think DrawEM should be set up such that it can work with either an ITK N4 application or the respective command of the ANTs installation. But in either case, this is a pipeline dependency rather than a build/runtime dependency.

For a convenient installation of DrawEM for inexperienced users, it is better to later think about automating installation steps using CMake + Python.

**Comment by amakropoulos** [comment]
Thank you, yes this was quite a hack :) !
I now install N4 (and ITK) using cmake (#21).
