### ISSUE TITLE
Doesn't handle .nii file

### ISSUE THREAD

**Issue by chrisk1** [MIRTK/DrawEM#13]
Running the segmentation on an uncompressed T2_brain.nii file gives the following error:

```
Cifstream::Open: Cannot open file T2/T2_brain.nii.gz
Error: convert-image command returned non-zero exit status 1
```

Converting the .nii to a compressed .nii.gz format works normally. An unimportant error check to add in perhaps!

**Comment by amakropoulos** [comment]
Thank you for spotting this :) !
This is now fixed in #21
