### ISSUE TITLE
Problem with atlases

### ISSUE THREAD

**Issue by Qdelannoy** [MIRTK/DrawEM#20]
Hi,

The link to the atlases needed for the segmentation don't lead me to an url where I can find the it. 

Can you help me please ?

Thanks

**Comment by amakropoulos** [comment]
Hi, 
Indeed the link doesn't exist anymore.
I'll fix that ASAP and update you!

**Comment by amakropoulos** [comment]
Hi there, 

The atlases can be found in:
https://biomedic.doc.ic.ac.uk/brain-development/downloads/dHCP/atlases-dhcp-structural-pipeline-v1.zip

**Comment by Qdelannoy** [comment]
Thank you !
