### ISSUE TITLE
Problem with labels-multi-atlas.sh

### ISSUE THREAD

**Issue by nnashka** [MIRTK/DrawEM#7]
Hi,

When trying to segment an image, I get an error in the labels-multi-atlas.sh script saying:
Histogram1D<HistogramType>::CDFToBin: Must be between 0 and 1
Error: normalize command returned non-zero exit status 1

It seems to be in the section: #weight atlas locally

Do you have any idea as to why I get this error?

Thanks!

**Comment by amakropoulos** [comment]
Hi,

Thank you for spotting this!

There is a typo in line 422 of Modules/Image/include/mirtk/Histogram1D.h :
"if (p < .0 || p > .1) {"
should be:
"if (p < .0 || p > 1.0) {"

It will be updated soon.

Antonis
